;; My packages

(prelude-require-packages '(ag
                            aggressive-indent
                            bundler
                            chruby
                            counsel
                            counsel-projectile
                            counsel-gtags
                            counsel-tramp
                            csv-mode
                            docker-tramp
                            dockerfile-mode
                            ess
                            ess-R-data-view
                            ess-smart-equals
                            feature-mode
                            flycheck-plantuml
                            forge
                            git-link
                            ggtags
                            groovy-mode
                            less-css-mode
                            ob-elixir
                            ob-http
                            ob-restclient
                            org
                            ;; org-plus-contrib
                            p4
                            plantuml-mode
                            poly-R
                            poly-erb
                            poly-org
                            poly-markdown
                            projectile-rails
                            rainbow-identifiers
                            restclient
                            rspec-mode
                            rubocop
                            ruby-tools
                            scad-mode
                            scad-preview
                            smart-mode-line
                            smex
                            toml-mode
                            treemacs
                            treemacs-magit
                            treemacs-projectile
                            wgrep
                            yasnippet))
